### ISSUE TITLE
Automatically reload the site if the user refreshes and the focus block end time is over

### ISSUE THREAD

**Issue by jeznag** [Focus-Bear/assets#113]
If the user was doing their morning routine/a focus block and a site was blocked, they expect to be able to reload the blocked page and get the original URL. Can we detect if the current tab has been reloaded (perhaps put the query string in local storage on the first load and then we'd be able to tell if the tab has been reloaded based on the presence of the local storage key) and redirect to the blocked URL if the focus block is over/it was a morning/evening routine?

**Comment by amanueltsfy** [comment]
Time estimation: <1 hour
