### ISSUE TITLE
Show instructions for changing always blocked URLs

### ISSUE THREAD

**Issue by jeznag** [Focus-Bear/assets#38]
We can tell when block-type=always-blocked (I think it's something like that).

Give the user instructions for how to change their blocked URLs.

"If you want to allow {url}, go to Preferences > Always Blocked URLs"

![CleanShot 2022-11-03 at 19 05 21](https://user-images.githubusercontent.com/1034890/199672205-14fc2ca7-c1d9-4b84-a573-6aa93a14312f.png)

**Comment by amanueltsfy** [comment]
resolved.
url: http://127.0.0.1:5500/focus-blocked/index.html?old_url=facebook.com&focus_mode=study&focus_mode_end_time=2022-11-16T07:33:38.387Z&block_type=always-block
![image](https://user-images.githubusercontent.com/11420548/208288872-ff103cbe-20f4-4d08-8d75-13fff3ae765f.png)

**Comment by jineyap4** [comment]
**QA Passed**

image has been changed to a hyperlink that leads to https://support.focusbear.io/portal/en/kb/articles/setting-up-always-blocked-sites-and-apps

**Browser:** Google Chrome
**Device:** Desktop - Windows 11 Pro 23H2

**Attachment:**


![Image](https://github.com/Focus-Bear/assets/assets/148239167/cf1cd2bf-a75a-42aa-86f6-f327b1e563e3)
