### ISSUE TITLE
Change view for Focus Block is over

### ISSUE THREAD

**Issue by jeznag** [Focus-Bear/assets#70]
<img width="818" alt="CleanShot 2022-12-18 at 11 43 17@2x" src="https://user-images.githubusercontent.com/1034890/208272407-373fd0cd-b107-4ff8-835f-dcb18d38494c.png">

Don't show the "Want to reprogram your habits..." part

**Comment by amanueltsfy** [comment]
resolved.
url: http://127.0.0.1:5500/focus-blocked/index.html?old_url=facebook.com&focus_mode=study&focus_mode_end_time=2022-11-16T07:33:38.387Z&block_type=always-block
![image](https://user-images.githubusercontent.com/11420548/208288545-af52c0c5-2fb9-4a7f-ad85-e606ad196bb8.png)

**Comment by amanueltsfy** [comment]
resolved
![image](https://user-images.githubusercontent.com/11420548/208289026-6854019d-e58b-465b-b914-b40115b35eea.png)

**Comment by jineyap4** [comment]
I tested this ticket and the issue cannot be reproduced anymore

**Tested on:** 

- Microsoft Edge - Version 118.0.2088.46 (Official build) (64-bit)
- FocusBear - Windows - 1.0.102

Device: Desktop - Windows 11
